config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :wikis

  resources :charges, only: [:new, :create]

  get 'users/destroy'

  get 'users/show'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis

  before_save { self.role ||= :standard }

  enum role: [:standard, :premium, :admin]

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create

    @amount = 10_00
    @user = current_user

    @user.update_attribute :role, "premium"
    @user.save!

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd',
    )

    flash[:notice] = "Thanks for subscribing!"
    redirect_to welcome_index_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path

  end

  def new
    @stripe_btn_data = {
      key: "#{
        Rails.configuration.stripe[:publishable_key]
      }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: Amount.default
    }
  end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def destroy
    @user = current_user
    @user.update_attribute :role, "standard"
    @user.save!

    @wikis = Wiki.where(user_id: @user.id)
    @wikis.update_all( private: false )

    redirect_to welcome_index_path
    flash[:alert] = "Premium membership deleted!"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.all
    @user = current_user
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new

    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    @wiki.user = current_user


    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error creating wiki."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
    @user = current_user
    @body = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@wiki.body)
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update

    @wiki = Wiki.find(params[:id])

    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error editing wiki."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "Wiki was deleted."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error deleting wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

  <h4>Upgrade to Premium!</h4>


    <script
      class='stripe-button'
      src='https://checkout.stripe.com/checkout.js'
      data-key='<%= @stripe_btn_data[:key] %>'
      data-amount='<%= @stripe_btn_data[:amount] %>'
      data-description='<%= @stripe_btn_data[:description] %>'
    ></script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flikipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <div class="menu">
        <%= link_to "Home", welcome_index_path %>
        <%= link_to "About", welcome_about_path %>
        <%= link_to "Wikis", wikis_path %>
      </div>
      <div class="user-account">
        <% if user_signed_in? %>
          <% if current_user.premium? %>
            <%= link_to "User Profile", users_show_path %>
          <% end %>
          <% if current_user.standard? %>
          <%= link_to "Upgrade to Premium!", new_charge_path %>
          <% end %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </div>
    </div>
    <%= yield %>

<!-- Flash messages recommended by Devise -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/users/show.html.erb
<h1>User Profile</h1>

<%= link_to "Cancel Premium Membership", users_destroy_path %>

app/views/welcome/about.html.erb
<p>
  Flikipedia is a wiki by Evan Flint
</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <h1>Flikipedia</h1>
    A Wiki that Charges People for Some Reason
</div>

app/views/wikis/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <%= form_for @wiki do |f| %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :body %><br>
        <%= f.text_area :body, rows: "8", cols: "50" %>
      </p>
      <% if current_user.admin? || current_user.premium? %>
        <p>
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %>
            Private wiki
            <% end %>
        </p>
      <% end %>
        <%= f.submit "Save", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <%= render partial: 'form', locals: { title: @wiki.title, body: @wiki.body } %>

app/views/wikis/index.html.erb
<h1>Wikis Index</h1>

<p><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %></p>

<% @wikis.each do |wiki| %>

  <% if wiki.private? %>
  <b><%= link_to wiki.title, wiki %></b> - Private<br>
  <% else %>
  <%= link_to wiki.title, wiki %><br>
  <% end %>

<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render partial: 'form', locals: { title: @wiki.title, body: @wiki.body, private: @wiki.private } %>

app/views/wikis/show.html.erb
<h1>Wiki Show</h1>

  <% if @wiki.private? && @user.standard? %>
    This Wiki is Private
  <% end %>

<h3><%= @wiki.title %></h3>


<% unless @wiki.private? && @user.standard? %>
  <%= @body.html_safe %>

  <p>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
  </p>
<% end %>